; /etc/supervisor/conf.d/agency-worker.conf
; supervisorctl reread && supervisorctl update && supervisorctl start agency-worker:*

[program:agency-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/agency/artisan queue:work --sleep=3 --tries=3 --max-time=3600
directory=/var/www/agency
autostart=true
autorestart=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/agency/storage/logs/worker.log
stopwaitsecs=3600
